### ISSUE TITLE
[Help Wanted] Arch + Hyprland

### ISSUE THREAD

**Issue by 0xSDX** [GrenicMars/dotfiles#1]
I recently came across this rice and it has since been on my mind. [Link](https://www.reddit.com/r/unixporn/comments/10xz677/hyprland_wayland_experience_on_a_nvidia_optimus/)
I have a similar family laptop (Legion Y540(i5/1650)). 
I intend to achieve :
- Replicating this rice with ArchLinux without actually installing a DE
- Proper Dual GPU Hardware drivers configured (iGPU+dGPU)
Do let me know, where I can contact you for the help and doubts. 

To : @GrenicMars thankyou for this awesome 🍚 showcase and configs.

**Comment by jetblack0** [comment]
You already contacted me on reddit so i will close this issue
